package internalErrors

func ValidateError(err error) error {
	return err
}
